<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 9px; color: #1a1a1a; }
        .page { width: 210mm; min-height: 297mm; padding: 5mm; }
        .grid-2x7 { display: table; width: 100%; border-collapse: separate; border-spacing: 2mm; }
        .grid-row { display: table-row; }
        .label-cell { display: table-cell; width: 50%; vertical-align: top; }

        .label {
            border: 1px solid #ccc;
            border-radius: 3px;
            padding: 3mm;
            height: 36mm;
            position: relative;
        }

        .logo-small { height: 6mm; }
        .test-name { font-size: 9px; font-weight: bold; color: #0B4EA2; margin-bottom: 1mm; }
        .step-info { font-size: 14px; font-weight: bold; color: #F58220; margin-bottom: 1mm; }
        .detail-row { margin-bottom: 0.5mm; font-size: 8px; }
        .detail-label { font-weight: bold; color: #555; }
        .velocity-lines { margin-top: 2mm; border-top: 1px solid #eee; padding-top: 1mm; }
        .velocity-line { border-bottom: 1px dotted #ccc; height: 4mm; margin-bottom: 1mm; font-size: 7px; color: #999; }
        .footer-text { font-size: 6px; color: #999; text-align: center; margin-top: 1mm; }
    </style>
</head>
<body>
@php
    $labels = $steps;
    $labelsPerPage = 14;
    $totalPages = ceil($labels->count() / $labelsPerPage);
@endphp

@for($page = 0; $page < $totalPages; $page++)
    <div class="page" @if(!$loop->last) style="page-break-after: always;" @endif>
        <div class="grid-2x7">
            @for($row = 0; $row < 7; $row++)
                @php $idx = $page * $labelsPerPage + $row * 2; @endphp
                @if($idx < $labels->count())
                    <div class="grid-row">
                        @for($col = 0; $col < 2; $col++)
                            @php $labelIdx = $idx + $col; $step = $labels->values()->get($labelIdx); @endphp
                            <div class="label-cell">
                                @if($step)
                                    <div class="label">
                                        <div style="text-align: center; margin-bottom: 1mm;">
                                            @if(file_exists(public_path('nrapa-logo.png')))
                                                <img src="{{ public_path('nrapa-logo.png') }}" class="logo-small">
                                            @else
                                                <span style="font-size: 8px; font-weight: bold; color: #0B4EA2;">NRAPA</span>
                                            @endif
                                        </div>
                                        <div class="test-name">{{ $test->name }}</div>
                                        <div class="step-info">Step {{ $step->step_number }} &mdash; {{ $step->charge_weight }}gr</div>

                                        @if($test->bullet_make || $test->bullet_weight)
                                            <div class="detail-row">
                                                <span class="detail-label">Bullet:</span>
                                                {{ $test->bullet_make }} {{ $test->bullet_weight ? $test->bullet_weight . 'gr' : '' }} {{ $test->bullet_type }}
                                            </div>
                                        @endif
                                        @if($test->primer_type)
                                            <div class="detail-row">
                                                <span class="detail-label">Primer:</span> {{ $test->primer_type }}
                                            </div>
                                        @endif

                                        <div class="velocity-lines">
                                            @for($v = 0; $v < min($test->rounds_per_step, 5); $v++)
                                                <div class="velocity-line">V{{ $v + 1 }}: ________</div>
                                            @endfor
                                        </div>

                                        <div class="footer-text">Generated by NRAPA Virtual Loading Bench</div>
                                    </div>
                                @endif
                            </div>
                        @endfor
                    </div>
                @endif
            @endfor
        </div>
    </div>
@endfor
</body>
</html>
